name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Swiftlint
      run: |
        brew install swiftlint
        swiftlint

    - name: cocoapods lint
      run: |
        pod lib lint --allow-warnings
